### ISSUE TITLE
ImportError: /home/ni/anaconda3/lib/python3.7/site-packages/neural_renderer/cuda/load_textures.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

### ISSUE THREAD

**Issue by onepiece666** [zengwang430521/DecoMR#10]
**when i run the eval.py on the lsp_test dataset.**

`/home/ni/anaconda3/bin/python /home/ni/DecoMR/eval.py --checkpoint=data/model/h36m_up3d/checkpoints/h36m_up3d.pt --dataset=lsp --log_freq=20
Checkpoint loaded
data loader finish
Traceback (most recent call last):
  File "/home/ni/DecoMR/eval.py", line 318, in <module>
    run_evaluation(model, args, options, args.dataset, args.log_freq)
  File "/home/ni/DecoMR/eval.py", line 122, in run_evaluation
    from utils.part_utils import PartRenderer
  File "/home/ni/DecoMR/utils/part_utils.py", line 7, in <module>
    import neural_renderer as nr
  File "/home/ni/anaconda3/lib/python3.7/site-packages/neural_renderer/__init__.py", line 3, in <module>
    from .load_obj import load_obj
  File "/home/ni/anaconda3/lib/python3.7/site-packages/neural_renderer/load_obj.py", line 8, in <module>
    import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: /home/ni/anaconda3/lib/python3.7/site-packages/neural_renderer/cuda/load_textures.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

Process finished with exit code 1`

Do you know the cause of this problem

**Comment by onepiece666** [comment]
Thanks, I solved the problem by git clone [https://github.com/daniilidis-group/neural_renderer.git](url) . 
`cd neural_renderer`  and run `python setup.py install`
