### ISSUE TITLE
AttributeError: 'ColoredRenderer' object has no attribute 'vbo_verts_face'

### ISSUE THREAD

**Issue by xmk2222** [zengwang430521/DecoMR#3]
```
Traceback (most recent call last):
  File "demo.py", line 140, in <module>
    img=img, use_bg=True, body_color='pink')
  File "/data/DecoMR/utils/renderer.py", line 351, in render
    return self.renderer.r
  File "/home/xumingkai/.local/lib/python3.6/site-packages/chumpy/ch.py", line 555, in r
    self._call_on_changed()
  File "/home/xumingkai/.local/lib/python3.6/site-packages/chumpy/ch.py", line 550, in _call_on_changed
    self.on_changed(self._dirty_vars)
  File "/home/xumingkai/.local/lib/python3.6/site-packages/opendr/renderer.py", line 1080, in on_changed
    self.vbo_verts_face.set_array(np.array(self.verts_by_face).astype(np.float32))
AttributeError: 'ColoredRenderer' object has no attribute 'vbo_verts_face'

**Comment by zengwang430521** [comment]
I'm sorry for the late reply. 
This may be a bug of opendr, and I falied to repeat this bug. Could you please provide more information?
